name: deployment
on: [push, workflow_dispatch]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm ci
      - name: npm lint
        run: npm run lint
      - name: npm test
        run: npm run test
      - name: npm run build
        run: npm run build
